### ISSUE TITLE
doesn't work with theme options snippet

### ISSUE THREAD

**Issue by mac2net** [florianbeck/cmb2-field-type-tags#2]
Hi
I want to use this with a hacked version of the theme option snippet used for a plugin options page.

My other CMB2 fields and also the multcheck_posttype field are working fine.

Any ideas?

Cheers
Mike

**Comment by mac2net** [comment]
Is this a "never gonna work" or "you must self-heal" or playing with this is "self-harm"?

**Comment by mac2net** [comment]
Never mind, I figured it out. Happy to post my solution her once I know a human is watching.

**Comment by florianbeck** [comment]
Hi mac2net, this plugin is not maintained at the moment, I'm sorry. But please feel free to post or commit your update. Greetings, Florian.

**Comment by mac2net** [comment]
OK, for what seems to be for better and hopefully not worse I enqueued the core tags-box script to get this to work on an options page.

```
function cmb_tags_enqueue() {
    wp_enqueue_script( 'cmb_tags_script', CMB_TAGS_URL . 'js/tags.js', array( 'jquery', 'jquery-ui-sortable' ), CMB_TAGS_VERSION );
    wp_enqueue_script( 'tags-box');
    wp_enqueue_style( 'cmb_tags_stype', CMB_TAGS_URL . 'css/tags.css', array(), CMB_TAGS_VERSION );
}
```

**Comment by florianbeck** [comment]
Thank's mac2net for this solution.
